# DFtpS - FTP Server Configuration File
# https://github.com/MNLaugh/dftps

[addr]
  port = 21
  # hostname = "127.0.0.1"

[options]
  # debug = true
  # URL for passive connection
  pasvUrl = "127.0.0.1"
  # Minimum port for passive connection
  pasvMin = 1024
  # Maximum port for passive connection
  pasvMax = 65535
  # Handle anonymous connection (true | false)
  # anonymous = false
  # Sets the format to use for file stat queries such as "LIST"
  # fileFormat = ""
  # Array of commands that are not allowed
  # blacklist = ["DELE", "RMD"]
  # URL of webhook (e.g., Discord webhook)
  # webhook = "https://discord.com/api/webhooks/..."

# TLS Configuration (optional)
# [tls]
#   certFile = "./cert.pem"
#   keyFile = "./key.pem"

[database]
  # SQLite database configuration
  connector = "SQLite"
  filepath = "./dftps.db"
